### ISSUE TITLE
When I yank, the copied text has not been added to system clipboard

### ISSUE THREAD

**Issue by Miroshni4enko** [AndrewRadev/yankwin.vim#1]
Looks like the plugin does not copy text to '+' register.
OS Ubuntu 18.04.3 LTS
Neovim

**Comment by AndrewRadev** [comment]
The plugin *should* yank to the `+` register if you have `unnamedplus` in your [`'clipboard'`](https://vimhelp.org/options.txt.html#%27clipboard%27) setting, so something like this:

``` vim
set clipboard=unnamedplus
```

If you want to yank to *both* `+` and `*` clipboards, you could even put this in your configuration instead:

``` vim
set clipboard=unnamed,unnamedplus
```

However, this will make Vim paste from `+` by default, not from `*`. To make it possible to control this, I've just pushed a setting called `g:yankwin_yank_clipboard` that you can set instead of the the global `clipboard`. You should be able to find more info in the documentation.

<hr>

However, if you *do* have `unnamedplus` in your 'clipboard' setting (or the new plugin setting) and the plugin is still not yanking to `+`, there must be a bug. Could you let me know if that's the case? Also, if it is a bug, it would be useful for me to see the output of your `vim --version`.

**Comment by Miroshni4enko** [comment]
I've added `set clipboard=unnamedplus` and everything works now, thank you!)
